name: Metrics
on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Comment reactions
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.reactions.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_reactions: yes
        plugin_reactions_limit: 100
        plugin_reactions_details: percentage
    - uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
    - name: Full-year calendar
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.isocalendar.fullyear.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
